### ISSUE TITLE
unexpected success should not be ok, should it?

### ISSUE THREAD

**Issue by mcepl** [python-tap/tappy#136]
tap.py 3.1 and I get these lines on the output:

```
ok 335 test_date_after_2050_working (tests.test_x509.X509TestCase.test_date_after_2050_working) # TODO (unexpected success)
ok 336 x509_get_not_before() and x509_get_not_after() return internal # TODO (unexpected success)
```

How can `unexpected success` be `ok`?

**Comment by mblayman** [comment]
tappy tries to adhere to the TAP spec (in this case, version 13).

> Note that if the TODO has an explanation it must be separated from TODO by a space. These tests represent a feature to be implemented or a bug to be fixed and act as something of an executable “things to do” list. They are not expected to succeed. _Should a todo test point begin succeeding, the harness should report it as a bonus._ This indicates that whatever you were supposed to do has been done and you should promote this to a normal test point.

(emphasis added)

https://testanything.org/tap-version-13-specification.html#todo-tests

**Comment by mcepl** [comment]
> > Note that if the TODO has an explanation it must be separated from TODO by a space. These tests represent a feature to be implemented or a bug to be fixed and act as something of an executable “things to do” list. They are not expected to succeed. _Should a todo test point begin succeeding, the harness should report it as a bonus._ This indicates that whatever you were supposed to do has been done and you should promote this to a normal test point.

Right, good for you. That unfortunately means that `tappy` effectively hides bad behaviour from me, so although I am a big friend of TAP format (and author of older and now completely abandoned couple of `yamlish`/`bayeux`), I have to switch to the plain `unittest`. Oh well.

**Comment by mblayman** [comment]
Hi, @mcepl, as written, your comment feels very snarky to me. I tried to provide an honest answer, backed by what I believe to be an accurate interpretation of the TAP version 13 specification.

I'm sorry that doesn't provide you with the behavior that you're looking for. I have documented alternatives of packages that you may find fit your needs. https://tappy.readthedocs.io/en/latest/alternatives.html

Best of luck.

**Comment by mcepl** [comment]
I didn’t mean to be snarky. I understand your problem, you want to follow the specification (which is of course The Right Thing™ to do), but unfortunately the result has catastrophic consequences to me (hiding bugs). And no the alternatives won’t work for me, because apparently there is a problem in the specification.

**Comment by mblayman** [comment]
Yeah, I understand where you're coming from too. It's a weird part of the spec for sure. Thanks for the response.
