### ISSUE TITLE
Make parser understand YAML diagnostics for TAP version 13

### ISSUE THREAD

**Issue by mblayman** [python-tap/tappy#17]
TAP version 13 added optional YAML blocks to tests. Everything else about the spec stayed the same. If the TAP parser was updated to support YAML blocks, then tappy could be considered version 13 "compliant" (even though YAML blocks never had any formally defined schema).

**Comment by arewm** [comment]
I was thinking about trying to make `tappy` version 13 compliant. Do you have any thoughts/preferences about how this should be done? 

From what I understand, IF `TAP version 13` is the first line, parsing will have to change in the following ways:
* If a diagnostic line happens between test and yaml, it will be linked to the previous result
* If a yaml section is read in, it will be linked to the previous result

Should the diagnostic line be removed as its own type and always be associated with the test before?

**Comment by mblayman** [comment]
I re-read the spec to confirm: diagnostics behavior remains the same. They should *not* be associated with a previous line.

I guess the important thing to note is that diagnostics and YAML blocks are two distinct things.

I agree with your second bullet.

>Diagnostics
>
>Additional information may be put into the testing output on separate lines. Diagnostic lines should begin with a #, which the harness must ignore, at least as far as analyzing the test results. The harness is free, however, to display the diagnostics. TAP13’s YAML blocks are intended to replace diagnostics for most purposes but TAP13 consumers should maintain backwards compatibility by supporting them.

If you go down this path (which would be awesome, btw), I'd like the dependency on YAML to be optional. In the presence of TAP 13 output, there could be a runtime check that would issue a warning that YAML will be ignored if the YAML library is not installed.

I could ultimately add an optional section to the packaging so that installing tappy with `tap.py[yaml]` or `tap.py[13]` would add the extra behavior. That part could be up for discussion.

**Comment by mblayman** [comment]
Yep, there is ambiguity in the standard which is why TAP 14 was proposed (though it hasn't moved anywhere for years).

I would like to have a strict interpretation where a YAML block is only considered if it immediately follows a result line. I think that is likely to be easier to code.

No, I was not reserving `result.diagnostic`. A diagnostic line is its own type and should remain that way (http://tappy.readthedocs.io/en/latest/consumers.html#tap.line.Diagnostic). To avoid confusion, I think the result line should have `result.yaml_block`. There is no schema for the YAML block so I don't want to shoehorn it into `diagnostic` if the spec ultimately decides that it's some kind of general purpose data structure (for instance, a YAML block could include stuff like timing data).

> Currently (2007/03/17) the format of the data structure represented by a YAML block has not been standardized. It is likely that whatever schema emerges will be able to capture the kind of forensic information about a test’s execution seen in the example above.

pip has the ability to specify optional dependencies using the bracket format. No need to worry about that part. I can make the packaging change later.

**Comment by arewm** [comment]
I understand that a diagnostic line is valid, but I was referring to the `tap.line.Result.diagnostics`. It is in the code as a member variable but is only present in the documentation as a parameter ([https://tappy.readthedocs.io/en/latest/consumers.html#tap.line.Result](https://tappy.readthedocs.io/en/latest/consumers.html#tap.line.Result)). It is probably not in the documentation as it is not an exposed property. Additionally, when you create a `Result`, you never pass it in.

I hope to look into Version 13 support in the next little bit, but I will try to keep you updated.

**Comment by mblayman** [comment]
You know you've been working on a project for too long when you totally forget about a feature. 😄 

Looks like `diagnostics` are passed in for `Tracker.add_not_ok`. The `TAPTestResult` formats the exception and passes that in as diagnostic output. Looks like `nose-tap` and `pytest-tap` also pass in the diagnostics on an error.

**Comment by mblayman** [comment]
I guess this reinforces my thought that YAML stuff should go on `result.yaml_block`.

**Comment by arewm** [comment]
I now have a reason to charge time to making tappy Version 13 compliant, so I should get to it in the next week. 😁

**Comment by mblayman** [comment]
Neat!

**Comment by arewm** [comment]
@mblayman thanks for letting me work on this, it was fun! 😄

**Comment by mblayman** [comment]
@arewm Thanks so much for your help! I'm not sure I would have ever found the time to add version 13 support myself so I'm really grateful for what you did. I hope your first big open source contribution experience was a good one!

FYI, I just released 2.3 to PyPI so you can now enjoy the fruits of your labor via a `pip install`. 😄

**Comment by arewm** [comment]
It was definitely good. Now I have a legitimate experience to answer all of those job application questions about contributing to Open Source projects. 😁

**Comment by mblayman** [comment]
![success](http://i0.kym-cdn.com/photos/images/facebook/000/011/296/success_baby.jpg)
