### ISSUE TITLE
Info about use

### ISSUE THREAD

**Issue by ric79** [python-tap/tappy#67]
Hello,
I developed a program for testing the network behaviour (in python). In normal run it actually checks conditions and if they are not satisfied it updates an error log file.

Can I "produce" TAP file dinamically from my code?
Something like
```
tap = newTapTestCase(...)
if !condition:
  tap.addError(...)
else:
  tap.addOk(...)
tap.close()
```
Riccardo

**Comment by mblayman** [comment]
tappy was designed with Python testing frameworks in mind so the internal tracking is not really exposed as public API. The closest thing to what you are looking for in tappy is the `Tracker` (https://github.com/python-tap/tappy/blob/master/tap/tracker.py) which has an API that supports `add_ok`, `add_not_ok`, and `add_skip`. I think the streaming mode would be closest to what you'd need. Something like:
```python
from tap.tracker import Tracker

tracker = Tracker(streaming=True, stream=my_open_error_file)
tracker.add_ok('SomeTestCase', 'This is the test description')
```
You may also want to consider alternative TAP projects (http://tappy.readthedocs.io/en/latest/alternatives.html) as one of them might have an API closer to what you're looking for.

Good luck!

**Comment by ric79** [comment]
Thanks

**Comment by arewm** [comment]
@mblayman I was hoping to use tappy as a TAP consumer to parse a TAP output and convert it to another format (i.e. json). I see that none of the loader/parser functionality is a public API. Does your comment mean that my use case is out of scope for tappy?

**Comment by mblayman** [comment]
@arewm The loader and parser *are* public API. Maybe you missed them. You can find the docs for those here: http://tappy.readthedocs.io/en/latest/consumers.html#api

What I was saying is not public API is the `Tracker` class which is used on the producer side. You're welcome to use the `Tracker` in whatever way you see fit with the caveat that if something breaks, you get to keep the pieces. 😄

**Comment by arewm** [comment]
@mblayman Thanks. I was hoping that tappy supported what I wanted. I think it will be much better than trying to figure out how to accomplish the same thing in nodejs!

I was just being stupid and did not perform the correct import. I could not find the classes with `import tap` or `from tap import *`, but it did work once I imported them directly `from tap import loader`; `from tap import parser`. 😬

**Comment by mblayman** [comment]
Cool! Best of luck to you!
